### ISSUE TITLE
Update outdated dependencies

### ISSUE THREAD

**Issue by eddrichjanzzenang** [eddrichjanzzenang/alpha-blog#1]
Please help me update outdated dependencies in the Gem file

**Comment by lisaychuang** [comment]
Hi @eddrichjanzzenang , I can help take a look at this issue :)

Using `bundle outdated` [(see docs here)](https://bundler.io/v1.3/bundle_outdated.html), see below for the list of your outdated gems. I see that you do have some tests, please let me know what commands I should use to run tests as I upgrade your gems?

Outdated gems included in the bundle:
  * actioncable (newest 5.2.1, installed 5.0.1)
  * actionmailer (newest 5.2.1, installed 5.0.1)
  * actionpack (newest 5.2.1, installed 5.0.1)
  * actionview (newest 5.2.1, installed 5.0.1)
  * activejob (newest 5.2.1, installed 5.0.1)
  * activemodel (newest 5.2.1, installed 5.0.1)
  * activerecord (newest 5.2.1, installed 5.0.1)
  * activesupport (newest 5.2.1, installed 5.0.1)
  * arel (newest 9.0.0, installed 7.1.4)
  * autoprefixer-rails (newest 9.1.4, installed 6.5.1.1)
  * bcrypt (newest 3.1.12, installed 3.1.11, requested ~> 3.1.7) in groups "default"
  * bootstrap-will_paginate (newest 1.0.0, installed 0.0.10) in groups "default"
  * builder (newest 3.2.3, installed 3.2.2)
  * byebug (newest 10.0.2, installed 9.0.6) in groups "development, test"
  * coffee-rails (newest 4.2.2, installed 4.2.1, requested ~> 4.2) in groups "default"
  * concurrent-ruby (newest 1.0.5, installed 1.0.3)
  * debug_inspector (newest 0.0.3, installed 0.0.2)
  * ffi (newest 1.9.25, installed 1.9.14)
  * globalid (newest 0.4.1, installed 0.3.7)
  * i18n (newest 1.1.0, installed 0.7.0)
  * jbuilder (newest 2.7.0, installed 2.6.1, requested ~> 2.5) in groups "default"
  * jquery-rails (newest 4.3.3, installed 4.2.1) in groups "default"
  * listen (newest 3.1.5, installed 3.0.8, requested ~> 3.0.5) in groups "development"
  * loofah (newest 2.2.2, installed 2.0.3)
  * mail (newest 2.7.0, installed 2.6.4)
  * method_source (newest 0.9.0, installed 0.8.2)
  * mime-types (newest 3.2.2, installed 3.1)
  * mime-types-data (newest 3.2018.0812, installed 3.2016.0521)
  * mini_portile2 (newest 2.3.0, installed 2.1.0)
  * minitest (newest 5.11.3, installed 5.10.1)
  * multi_json (newest 1.13.1, installed 1.12.1)
  * nio4r (newest 2.3.1, installed 1.2.1)
  * nokogiri (newest 1.8.4, installed 1.6.8.1)
  * pg (newest 1.1.3, installed 0.19.0) in groups "production"
  * puma (newest 3.12.0, installed 3.6.2, requested ~> 3.0) in groups "default"
  * rack (newest 2.0.5, installed 2.0.1)
  * rack-test (newest 1.1.0, installed 0.6.3)
  * rails (newest 5.2.1, installed 5.0.1, requested >= 5.0.0.1, ~> 5.0.0) in groups "default"
  * rails-controller-testing (newest 1.0.2, installed 1.0.1) in groups "default"
  * rails-dom-testing (newest 2.0.3, installed 2.0.1)
  * rails-html-sanitizer (newest 1.0.4, installed 1.0.3)
  * railties (newest 5.2.1, installed 5.0.1)
  * rake (newest 12.3.1, installed 12.0.0)
  * rb-fsevent (newest 0.10.3, installed 0.9.8)
  * rb-inotify (newest 0.9.10, installed 0.9.7)
  * sass (newest 3.6.0, installed 3.4.23)
  * sass-rails (newest 5.0.7, installed 5.0.6, requested ~> 5.0) in groups "default"
  * spring (newest 2.0.2, installed 2.0.0) in groups "development"
  * sprockets (newest 3.7.2, installed 3.7.1)
  * sprockets-rails (newest 3.2.1, installed 3.2.0)
  * sqlite3 (newest 1.3.13, installed 1.3.12) in groups "development, test"
  * thor (newest 0.20.0, installed 0.19.4)
  * thread_safe (newest 0.3.6, installed 0.3.5)
  * tilt (newest 2.0.8, installed 2.0.5)
  * turbolinks (newest 5.2.0, installed 5.0.1, requested ~> 5) in groups "default"
  * turbolinks-source (newest 5.2.0, installed 5.0.0)
  * tzinfo (newest 1.2.5, installed 1.2.2)
  * uglifier (newest 4.1.19, installed 3.0.4) in groups "default"
  * web-console (newest 3.7.0, installed 3.4.0) in groups "development"
  * websocket-driver (newest 0.7.0, installed 0.6.4)
  * websocket-extensions (newest 0.1.3, installed 0.1.2)
  * will_paginate (newest 3.1.6, installed 3.1.0) in groups "default"
